# Generated by Django 5.2 on 2025-05-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
