# Generated by Django 5.2 on 2025-06-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admin_status_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.CharField(choices=[('logged in', 'Logged in'), ('logged off', 'Logged off'), ('lunch', 'Lunch'), ('brb', 'BRB')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('logged in', 'Logged in'), ('logged off', 'Logged off'), ('lunch', 'Lunch'), ('brb', 'BRB')], default='active', max_length=20),
        ),
    ]
