# Generated by Django 5.2 on 2025-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_admin_status_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('brb', 'BRB'), ('lunch', 'Lunch'), ('meeting', 'Meeting')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('brb', 'BRB'), ('lunch', 'Lunch'), ('meeting', 'Meeting')], default='available', max_length=20),
        ),
    ]
