# Generated by Django 5.2 on 2025-06-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_admin_status_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='Admin User', max_length=255),
        ),
    ]
