# Generated by Django 5.2 on 2025-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_admin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('posted_by', models.CharField(max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.CharField(choices=[('logged in', 'Logged In'), ('logged off', 'Logged off'), ('busy', 'Busy'), ('brb', 'BRB'), ('lunch', 'Lunch'), ('meeting', 'Meeting')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('logged in', 'Logged In'), ('logged off', 'Logged off'), ('busy', 'Busy'), ('brb', 'BRB'), ('lunch', 'Lunch'), ('meeting', 'Meeting')], default='available', max_length=20),
        ),
    ]
