# Generated by Django 5.2 on 2025-06-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notice_alter_admin_status_alter_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('access', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('guest', 'Guest')], default='guest', max_length=10)),
                ('shift', models.CharField(blank=True, max_length=10, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('logged in', 'Logged In'), ('logged off', 'Logged Off'), ('busy', 'Busy'), ('brb', 'BRB'), ('lunch', 'Lunch'), ('meeting', 'Meeting')], default='logged off', max_length=20)),
                ('reset_token', models.CharField(blank=True, max_length=64, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('teams_chat_link', models.URLField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/sample.png', null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
