# Generated by Django 5.2 on 2025-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_delete_admin_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reporting_manager',
            field=models.CharField(blank=True, choices=[('aravindh_sarvalingham', 'Aravindh Sarvalingham'), ('sornambigai', 'Sornambigai')], max_length=100, null=True),
        ),
    ]
